### ISSUE TITLE
Can no more scroll or click on the page after onSuccess

### ISSUE THREAD

**Issue by KevinOl** [datatrans/react-datatrans-light-box#11]
Hi,

after placing an order and being redirected to the order success page, I cannot click or scroll anymore.
Inspecting the dom, I can see that some styles set on the body and html (eg. overflow hidden) elements are not removed .
Also, data property 'data-datatrans-payment-lock' is still set to 'locked' on the html element.
Besides, the element 'paymentFrameWrapper' is set as 'display: block' with an overflow hidden.

In console I am getting, 

`VM298093 onloadwff.js:58 Uncaught TypeError: Cannot read property 'teardown' of undefined
    at Object.o.teardown (onloadwff.js:58)
    at onloadwff.js:58`

I googled a bit and it seems something related to lastpass chrome extension. I re-tested in incognito mode but still same. Cannot click nor scroll.

Idea?

PS: I upgraded to 2.0.1, removed usage of HoC

**Comment by pstadler** [comment]
Kevin, could it be that you're implementing dynamic routing using hash (e.g. `/#/orders/success`)? 
In any case, please try to register an `onSuccess` handler which calls `window.Datatrans.close()`.

**Comment by pstadler** [comment]
Sorry, I meant `onCancelled` (I know this sounds weird).

Update: If this doesn't work and you're using hash-based routing indeed, try also to call `window.Datatrans.close()` on your success page.

**Comment by KevinOl** [comment]
Hi Patrick,

thanks for your prompt answer.

So, onCancelled did not work but onSuccess worked.
Is this something that needs to be fixed for next release? I did not need to do that before.

Regards

**Comment by pstadler** [comment]
Well, the iFrame is now controlled by an external JavaScript. I guess you
should keep it like this for the time being. Will leave this ticket open
until I‘ve made up my mind whether and how this should be solved.

**Comment by martinestigarribiakognitiv** [comment]
Hi! Yes, It's the same for me. If you close the Lightbox with the arrow in the upper left corner, the Lightbox is closed but you can't use the page anymore. You must hand delete: 
- the attribute `data-datatrans-payment-lock` and the attribute `style` from the `html` tag, 
- the attribute `style` from the `body` tag
- the `#paymentFrameWrapper` div

The code I used is something like this:
```
const datatransIframe = document.querySelector('#paymentFrameWrapper');
if (datatransIframe && datatransIframe.parentNode !== null) {
    datatransIframe.parentNode.removeChild(datatransIframe);
}
document.querySelector('html').removeAttribute('data-datatrans-payment-lock');
document.querySelector('html').removeAttribute('style');
document.querySelector('body').removeAttribute('style');
```
Hope fix the bug soon...

**Comment by pstadler** [comment]
Thanks for your feedback. We aim to push a fix until the end of this week.

**Comment by pstadler** [comment]
@martinestigarribiakognitiv I don't quite understand how this can happen. When a payment is cancelled, the page should be unlocked automatically. Please help me to reproduce this by answering the following questions:

- What version are you using?
- How are you using this component? Could you give me some code snippets?
- With which payment methods is this happening? (e.g. Mastercard, PayPal, Twint...)

**Comment by pstadler** [comment]
2.0.2 has been released on NPM ([Changelog](https://github.com/datatrans/react-datatrans-light-box/releases/tag/2.0.2)).

@KevinOl please upgrade to this version and remove your workaround.
@martinestigarribiakognitiv I'm still not sure whether your problem is of a different nature, but I'm positive that 2.0.2 could fix your problem as well.

Happily awaiting feedback from both of you 👍

**Comment by martinestigarribiakognitiv** [comment]
@pstadler Yeah! Now is fixed! :) 

Now, `data-datatrans-payment-lock` value is `unlocked`, the `style` of `html` and `body` tags are cleaned up and the Iframe is removed from the body. All these things didn't happen in the previous version when the lightbox was closed either because you cancelled the payment or because the payment was satisfactory....

Thank you very much for your quick attention and resolution of the problem!

**Comment by KevinOl** [comment]
Hi @pstadler,

yep v2.0.2 works for me too.

I have not noticed any other issues so far ;-)

Thanks for your quick response!

Regards

**Comment by pstadler** [comment]
Glad to hear that. Thanks for your feedback :beers:
