### ISSUE TITLE
Error while parsing the 'sandbox' attribute: 'null' is an invalid sandbox flag.

### ISSUE THREAD

**Issue by flocbit** [datatrans/react-datatrans-light-box#15]
Hi guys!

One of our customers just ran into an issue which I can not reproduce at the moment: 

```datatrans-2.0.0.min.js:1 Error while parsing the 'sandbox' attribute: 'null' is an invalid sandbox flag.
(anonymous) @ datatrans-2.0.0.min.js:1

upStart.jsp:1 Blocked script execution in 'https://pay.datatrans.com/upp/jsp/upStart.jsp' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

upStart.jsp:76 Blocked script execution in 'https://pay.datatrans.com/upp/jsp/upStart.jsp' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

upStart.jsp:1 Blocked script execution in 'https://pay.datatrans.com/upp/jsp/upStart.jsp' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
```

After investigating the related file I found the attribute `datatransPaymentConfig.sandboxAttributeEnabled` which is disabled by default but seems to be responsible for setting the sandbox property. Is there a way to enable the required sandbox attributes using `Lightbox` component props or is that the intended behaviour?

Thanks for your help!

**Comment by pstadler** [comment]
I'm happy to tell you that this issue has been resolved today with a new software release (at around 14:30 CEST to be exact). No action required. Thanks for your report, feel free to ask further questions.

**Comment by flocbit** [comment]
Great to hear and thanks for your quick reply!
