### ISSUE TITLE
Config object params

### ISSUE THREAD

**Issue by romainwidmer** [datatrans/react-datatrans-light-box#19]
I noticed that I cannot pass any config object to the Lightbox component anymore.

let config = {
    transactionId: 'xxx-xxx-xxx-xxx',
    refno: 'xxx-xxx-xxx',
    amount: 5000,
    currency: 'CHF',
    production: false,
    paymentMethod: ['ECA', 'VIS', 'TWI'],
    autoSettle: true,
    themeConfiguration: {
        brandColor: '#FFD32F'
    }
}

<Lightbox
    {...config}
    onLoaded={onLoaded}
    onOpened={onOpened}
    onCancelled={onCancelled}
    onError={onError}
    amount={500}
/>

**Comment by pstadler** [comment]
As of version 3.0.0, this component is using the new Payment JSON API.

Payment docs: https://docs.datatrans.ch/docs/redirect-lightbox
API Docs: https://api-reference.datatrans.ch/
Component release notes: https://github.com/datatrans/react-datatrans-light-box/releases/tag/3.0.2

You can safely stay on 2.x in the meantime and continue to use the previous APIs.
