### ISSUE TITLE
Cannot read properties of undefined (reading 'startPayment')

### ISSUE THREAD

**Issue by cini9** [datatrans/react-datatrans-light-box#23]
Hi Datatrans,

Thanks a bunch for this library and the quick integration into React.

I am facing an issue where I am getting an error message, followed by the lightbox appearing a couple seconds later.

![Screenshot 2022-10-05 at 16 04 53](https://user-images.githubusercontent.com/56114997/194080327-eca95857-81c3-4232-ab40-f9891f812222.png)

![Screenshot 2022-10-05 at 16 05 29](https://user-images.githubusercontent.com/56114997/194080448-822c9b66-e52d-472d-9dbb-5ec57ada7030.png)

If I integrate the script given in the datatrans documentation (<script src="https://pay.sandbox.datatrans.com/upp/payment/js/datatrans-2.0.0.js">), the lightbox shows up but I cannot click anywhere on the lightbox

I am currently building a Web Application with :
Nextjs v 12.3.0
React v 18.2.0
react-datatrans-light-box v 3.1.0

**Comment by pstadler** [comment]
I've never seen this before. Does the example work for you? (`npm run example:start`)
Can you share some code for us to reproduce this?

**Comment by n3ssi3** [comment]
Looks to me like something is re-rendering your view. Please check out our example and your lifecycles.
If the problem persists, provide us with a reproducible code sample.

**Comment by jodast** [comment]
I'm running into the same issue using react 18.2.0.
I can reproduce the issue with your example after upgrading to react 18.2.0 (and changing 
`ReactDom.render(
  <App />,
  document.getElementById('app')
)`
to 
`ReactDOM.createRoot(document.getElementById("app")).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`

![image](https://user-images.githubusercontent.com/18407056/195129446-97185cc2-9ff6-49a3-b0c1-57fdf1367486.png)

**Comment by pstadler** [comment]
This should be fixed with 3.2.0 (already released). Please re-open this issue if it still happens.

Thanks for your report! 🍻
