### ISSUE TITLE
doesn't work if requireJS is on the page

### ISSUE THREAD

**Issue by jantimon** [datatrans/react-datatrans-light-box#25]
hi!

the react-datatrans-light-box integration fails if a `define` function is attached to the window because of the [umd](https://github.com/umdjs/umd) wrapper is used in datatrans:

![amd](https://user-images.githubusercontent.com/4113649/225547574-cc052f2d-4ec5-4ab2-9208-6c5dbefb6ffa.jpg)

would it be possible to bundle datatrans right into this package?

```js
const getDatatrans = (production) => 
  production 
     ? import('./datatrans-2.0.0.min.js')
     : import('./sandbox-datatrans-2.0.0.min.js')
}
```

**Comment by pstadler** [comment]
Hi Jan. We're trying to avoid this to retain the ability to urgently roll out updates due to security concerns or browser compatibility issues.

Don't hesitate to reopen this issue if you have further remarks 👍🏻

**Comment by jantimon** [comment]
@pstadler thanks for your quick response.

the Unified Module Definition (UMD) pattern used in https://pay.datatrans.com/upp/payment/js/datatrans-2.0.0.js is causing problems for us. the problem for us is the Asynchronous Module Definition (AMD) part as it starts connecting to other third party scripts on our page which are unfortunately using AMD too.

Shipping `UMD` feels quite out of date especially now that you say that the CommonJs part (which can only be used by bundlers) must not be used.

Would it be possible to provide an additional asset which would provide only the global api `window.Datatrans`?
https://pay.datatrans.com/upp/payment/js/datatrans-2.0.0.global.js

That way we could have a propper react hook integration.  
I haven't tested it but it could look (more or less) like this:

```tsx
const scripts = {
  prod: "https://pay.datatrans.com/upp/payment/js/datatrans-2.0.0.global.min.js",
  dev: "https://pay.sandbox.datatrans.com/upp/payment/js/datatrans-2.0.0.global.min.js"
};
let cache: Promise<IDatatrans> | undefined;

const getDatatrans = (mode: "prod" | "dev"): Promise<IDatatrans> => {
  if (!cache) {
     cache = new Promise((resolve, reject) => {
       const script = document.createElement("script");
       script.onload = () => { 
         document.head.removeChild(script);
         resolve(window.Datatrans);
       }
       script.onerror = reject;
       script.src = scripts[mode];
       document.head.appendChild(script);
     });
  }
  return cache;
}

/**
 * A hook which allows starting a Datatrans payment
 *  
 * The hook will download the payment javascripts from the Datatrans CDN.
 * The hook will automatically close the datatrans lightbox on unmount.
 */
export const useDatatrans = (mode: "prod" | "dev" = "prod") => {
  const [activeConfig, setActiveConfig] = useState<IDatatransConfig | null>(
    null
  );

  useEffect(() => {
    // We start to download the script even if activeConfig is null because we
    // want to start the download as soon as possible.
    const datatransPromise = getDatatrans(mode);

    if (!activeConfig) {
      return;
    }

    let active = true;
    let datatrans: IDatatrans | undefined;

    datatransPromise.then((loadModule) => {
      if (!active) {
        return;
      }
      datatrans = loadModule;
      datatrans.startPayment(activeConfig);
    });

    return () => {
      active = false;
      if (datatrans) {
        // Datatrans has a bug in the cleanup. If there is no paymentForm in the DOM it will fail to run removeChild.
        try {
          datatrans.close();
        } catch {
          // Ignore
        }
      }
    };
  }, [activeConfig]);

  return {
     startPayment: setActiveConfig, 
     close: () => setActiveConfig(null);
  }
};
```

maybe you could even publish such a hook with typings as `react-use-datatrans`.

Usage would be:

```tsx
const MyComponent = () => {
  const { startPayment } = useDatatrans();
  return <button onClick={() => startPayment({ /* config */ )}>
      Buy
  </button>
}
```

P.S.: sorry it's quite offtopic but the cleanup method called by `Datatrans.close` crashes if paymentForm is not mounted:
`paymentForm.parentNode.removeChild(paymentForm);`

**Comment by pstadler** [comment]
Thanks for your extensive report! You're absolutely right.
I'm adding this to our backlog, but can't give you an estimate.

If this is blocking you, my suggestion would be to additionally report this problem via your account manager at Datatrans.

**Comment by pstadler** [comment]
Reference: DT-20628

**Comment by jantimon** [comment]
Thank you for your time - I will reach out to our support contact 👍  

P.S.:
As you live in Zurich you might have used Galaxus.ch before.  
We run into this bug only in certain edge case situations.
But should you ever encounter that all products are silently removed from your cart during checkout - that's our Datatrans AMD issue 😉

**Comment by pstadler** [comment]
Luckily, I haven’t experienced this on my way to Level 25 😏

**Comment by pstadler** [comment]
We've deployed non-umd versions to sandbox and production. You won the naming-is-hard game 👍🏻 

**Sandbox**
https://pay.sandbox.datatrans.com/upp/payment/js/datatrans-2.0.0.global.js
https://pay.sandbox.datatrans.com/upp/payment/js/datatrans-2.0.0.global.min.js
**Production**
https://pay.datatrans.com/upp/payment/js/datatrans-2.0.0.global.js
https://pay.datatrans.com/upp/payment/js/datatrans-2.0.0.global.min.js

I'm going to close this, while still considering releasing this widget using a hook approach in the future. Please reopen it if something is off.

New version of this package will be released today.

**Comment by pstadler** [comment]
v3.3.0 has been published.
