### ISSUE TITLE
Error with paymentmethod attribute

### ISSUE THREAD

**Issue by jonyr** [datatrans/react-datatrans-light-box#7]
Hi Guys! Congrats for this library. We're using it in a full react application. I found an issue when passing the **paymentmethod**  parameters. 
I tried to pass them in two different ways 
 
`<Ligthbox paymentmethod="VIS,JCB,AMX" ... /> ` and 
`<Ligthbox paymentmethod={["VIS", JCB, AMX]} ... />`

The upStart.jsp endpoint requires multiple pamymentmethos query parameters as is shown below
_https://pilot.datatrans.biz/upp/jsp/upStart.jsp?<other_query_string_params>&paymentmethod=VIS&paymentmethod=AMX&paymentmethod=ECA_

But the function *toUrlParams*, located in src/utils.js line 18

```
export const toUrlParams = props => Object.keys(props)
.map(key => `${key}=${props[key]}`)
.join('&')

```

isn't handle them correctly.

Could you help me with this?
Thanks in advance.

**Comment by pstadler** [comment]
Thanks for reporting. This has been fixed with [1.0.8](https://github.com/datatrans/react-datatrans-light-box/releases/tag/1.0.8). Please upgrade to this version and pass parameters as an array, such as:

```js
<LightBox paymentmethod={['ECA', 'VIS', 'AMX']} />
```
